// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgessaoDeCarga.Context;

#nullable disable

namespace ProgessaoDeCarga.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250222140529_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProgessaoDeCarga.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Carga")
                        .HasColumnType("double");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int?>("TreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.SessaoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SessoesTreino");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.SessaoTreinoExercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("SessaoTreinoId")
                        .HasColumnType("int");

                    b.Property<int?>("TreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("SessaoTreinoId");

                    b.HasIndex("TreinoId");

                    b.ToTable("SessaoTreinoExercicios");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.Serie", b =>
                {
                    b.HasOne("ProgessaoDeCarga.Models.Exercicio", null)
                        .WithMany("Series")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgessaoDeCarga.Models.Treino", null)
                        .WithMany("Series")
                        .HasForeignKey("TreinoId");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.SessaoTreinoExercicio", b =>
                {
                    b.HasOne("ProgessaoDeCarga.Models.Exercicio", "Exercicio")
                        .WithMany("Sessao_Treino_Exercicios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgessaoDeCarga.Models.SessaoTreino", "SessaoTreino")
                        .WithMany("Sessao_Treino_Exercicios")
                        .HasForeignKey("SessaoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgessaoDeCarga.Models.Treino", null)
                        .WithMany("Sessao_Treino_Exercicios")
                        .HasForeignKey("TreinoId");

                    b.Navigation("Exercicio");

                    b.Navigation("SessaoTreino");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.Exercicio", b =>
                {
                    b.Navigation("Series");

                    b.Navigation("Sessao_Treino_Exercicios");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.SessaoTreino", b =>
                {
                    b.Navigation("Sessao_Treino_Exercicios");
                });

            modelBuilder.Entity("ProgessaoDeCarga.Models.Treino", b =>
                {
                    b.Navigation("Series");

                    b.Navigation("Sessao_Treino_Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
